/**
 * engine-bench — Phase 1 benchmark driver (docs/ECHO_STUDIO.md).
 *
 * Runs ONE build prompt through the self-hosted Grok Build engine (headless,
 * jailed) and records the evidence for the founder's side-by-side against
 * today's one-shot Echo. Run from the repo root:
 *
 *   npx tsx scripts/engine-bench.ts <name> "<build prompt>"
 *
 * First run also writes the engine home config (~ one time):
 *   - ANTHROPIC_API_KEY read from .env.local (never committed anywhere)
 *   - model "neugrid-claude" = claude-sonnet-5 via the Anthropic `messages`
 *     backend — the SAME brain Echo's one-shot uses, so the comparison
 *     isolates the HARNESS (workshop on vs. off), brain held constant.
 *   - telemetry off, auto-update off. config.toml is chmod 600, outside the repo.
 *
 * Outputs land in ~/Desktop/neugrid-engine/bench/<name>/ (the jailed workspace)
 * and ~/Desktop/neugrid-engine/bench/<name>.result.json (the evidence).
 */

import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { runEngineBuild, engineAvailable } from "../src/lib/engine";

const ROOT = path.join(os.homedir(), "Desktop", "neugrid-engine");
const HOME = path.join(ROOT, "home");
const BIN = process.env.NEUGRID_ENGINE_BIN || path.join(ROOT, "grok-build", "target", "release", "xai-grok-pager");
const MODEL_ID = process.env.NEUGRID_ENGINE_BRAIN || "claude-sonnet-5"; // the brain inside — Echo parity by default

function anthropicKey(): string {
  if (process.env.ANTHROPIC_API_KEY) return process.env.ANTHROPIC_API_KEY;
  try {
    const envFile = fs.readFileSync(path.join(process.cwd(), ".env.local"), "utf8");
    const m = envFile.match(/^ANTHROPIC_API_KEY=(.+)$/m);
    if (m) return m[1].trim();
  } catch { /* fall through */ }
  throw new Error("ANTHROPIC_API_KEY not found (env or .env.local)");
}

function ensureEngineHome(): void {
  fs.mkdirSync(HOME, { recursive: true });
  const cfg = path.join(HOME, "config.toml");
  const body = [
    `# NeuGrid engine home — generated by scripts/engine-bench.ts (chmod 600, never committed)`,
    `[cli]`,
    `auto_update = false`,
    ``,
    `[features]`,
    `telemetry = false`,
    ``,
    `[models]`,
    `default = "neugrid-claude"`,
    ``,
    `[model.neugrid-claude]`,
    `model = "${MODEL_ID}"`,
    `base_url = "https://api.anthropic.com/v1"`,
    `name = "NeuGrid brain (${MODEL_ID})"`,
    `api_backend = "messages"`,
    `context_window = 200000`,
    `max_completion_tokens = 16384`,
    `extra_headers = { "x-api-key" = "${anthropicKey()}", "anthropic-version" = "2023-06-01" }`,
    ``,
  ].join("\n");
  fs.writeFileSync(cfg, body, { mode: 0o600 });
  fs.chmodSync(cfg, 0o600);
}

async function main(): Promise<void> {
  const [name, ...promptParts] = process.argv.slice(2);
  const prompt = promptParts.join(" ").trim();
  if (!name || !prompt) {
    console.error(`usage: npx tsx scripts/engine-bench.ts <name> "<build prompt>"`);
    process.exit(1);
  }

  process.env.NEUGRID_ENGINE_BIN = BIN;
  process.env.NEUGRID_ENGINE_HOME = HOME;
  // The binary's startup gate wants an XAI_API_KEY present even when every model in
  // config.toml carries its own credentials (ours: Anthropic via extra_headers). A
  // placeholder satisfies the gate; nothing ever calls an xAI-hosted model with it.
  if (!process.env.XAI_API_KEY) process.env.XAI_API_KEY = "neugrid-selfhosted-placeholder";
  if (!engineAvailable()) {
    console.error(`engine binary not found at ${BIN} — is the compile done?`);
    process.exit(1);
  }
  ensureEngineHome();

  const workdir = path.join(ROOT, "bench", name);
  fs.rmSync(workdir, { recursive: true, force: true });
  fs.mkdirSync(workdir, { recursive: true });

  console.log(`▸ engine run "${name}" — brain ${MODEL_ID}, jailed at ${workdir}`);
  console.log(`▸ prompt: ${prompt.slice(0, 100)}${prompt.length > 100 ? "…" : ""}`);
  const t0 = Date.now();
  const res = await runEngineBuild({
    workdir,
    instruction:
      `${prompt}\n\nBuild it as a self-contained static web app in THIS directory: ` +
      `an index.html entry (inline or local css/js), no build step, no external network calls. ` +
      `Verify the core flows actually work (run/test them), fix what's broken — then STOP and summarize. ` +
      `Working and shippable beats gold-plated: no extra features, no endless polish.`,
    max_turns: 40,
    timeout_ms: 15 * 60_000,
  });
  // A max_turns cap-hit still leaves real, usually-working output in the workspace —
  // report it as capped, not failed (the run 1 lesson: it was polishing, not stuck).
  const capped = res.events.some((e) => e.type === "max_turns_reached");

  const summary = {
    name,
    prompt,
    brain: MODEL_ID,
    ok: res.ok || (capped && res.files_changed.length > 0), // capped-with-output = usable evidence
    capped,
    error: capped ? undefined : res.error,
    duration_s: +(res.duration_ms / 1000).toFixed(1),
    num_turns: res.num_turns,
    usage: res.usage,
    cost_usd: res.cost_usd,
    session_id: res.session_id,
    files_changed: res.files_changed,
    event_count: res.events.length,
    text_tail: res.text.slice(-600),
  };
  fs.writeFileSync(path.join(ROOT, "bench", `${name}.result.json`), JSON.stringify({ ...summary, events: res.events }, null, 2));

  console.log(`\n▸ done in ${summary.duration_s}s — ok=${res.ok}${res.error ? ` error=${res.error}` : ""}`);
  console.log(`▸ turns=${res.num_turns ?? "?"} cost=$${res.cost_usd?.toFixed(4) ?? "?"} events=${res.events.length}`);
  console.log(`▸ files (${res.files_changed.length}):`);
  for (const f of res.files_changed) console.log(`   ${f.kind.padEnd(8)} ${f.path} (${f.bytes}b)`);
  console.log(`▸ evidence: bench/${name}.result.json · workspace: bench/${name}/`);
  console.log(`  (wall-clock ${(Date.now() - t0) / 1000}s)`);
}

main().catch((e) => { console.error(e); process.exit(1); });
